apiVersion: v1
kind: Secret
metadata:
  name: local
  namespace: argocd
  labels:
     argocd.argoproj.io/secret-type: cluster
     environment: pre-staging
stringData:
  name: local
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }