apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-automated-sync
spec:
  destination:
    namespace: automated-sync
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argocd-applications/directoryOfmanifests
    repoURL: https://github.com/MiroslavSolar/ArgoCD.git
    targetRevision: master
  syncPolicy:
    automated: {}