apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-scratch
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: application-from-helm
      valueFiles:
      - custom-values.yaml
    path: argocd-applications/helm/nginx
    repoURL: https://github.com/MiroslavSolar/ArgoCD.git
    targetRevision: master