apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: project-1
  source:
    path: argocd-applications/helm/nginx
    repoURL: https://github.com/MiroslavSolar/ArgoCD.git
    targetRevision: master