apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-2
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'    
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  roles:
  - name: read-only
    description: "this role can be used for reading applications"
    policies: 
    - p, proj:project-2:read-only, applications, get, project-2/*, allow
