apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-3
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'    
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  roles:
  - name: read-sync
    description: "this role can be used for reading applications"
    policies: 
    - p, proj:project-3:read-sync, applications, get, project-3/*, allow
    - p, proj:project-3:read-sync, applications, sync, project-3/*, allow

